parameters:
    sonatra_doctrine_extensions.validator.unique_entity.class: Sonatra\Bundle\DoctrineExtensionsBundle\Validator\Constraints\UniqueEntityValidator
    sonatra_doctrine_extensions.validator.doctrine_callback.base.class: Sonatra\Bundle\DoctrineExtensionsBundle\Validator\Constraints\DoctrineCallbackValidator

services:
    sonatra_doctrine_extensions.validator.unique_entity:
        class:     '%sonatra_doctrine_extensions.validator.unique_entity.class%'
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: sonatra_doctrine_extensions.validator.unique_entity }

    sonatra_doctrine_extensions.validator.doctrine_callback:
        class:     '%sonatra_doctrine_extensions.validator.doctrine_callback.base.class%'
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: sonatra_doctrine_extensions.validator.doctrine_callback }
